@url=https://dayu-api.miaowoo.cc

### System
##### Info
GET {{url}}/info

##### Version
GET {{url}}/version

##### Events
GET {{url}}/events

### Swarm
@swarm={{url}}/swarm

##### Swarm Info
GET {{swarm}}/info

### Swarm Init
POST {{swarm}}/init

{}

### Stack
@stack={{url}}/stack
##### Stack List
GET {{stack}}/list
##### Stack Info
GET {{stack}}/faas
##### Stack Remove
POST {{stack}}/develop/remove


### Service
@service={{url}}/service
##### Service List
GET {{service}}/list
##### Service Info
GET {{service}}/3gchxsmjld0fuex216w56jl5g
##### Service Remove
POST {{service}}/develop/remove


### Container
@container={{url}}/container

##### Container logs
@id=6365041d2e52c5896dd14a5450920e482dddc33e6addaa07fab413bcda78d723
GET {{container}}/{{id}}/logs

### Dashboard
@dashboard={{url}}/dashboard

#####
GET {{dashboard}}